# Generated by Django 3.2.7 on 2022-01-02 13:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_product_api'),
    ]

    operations = [
        migrations.AddField(
            model_name='api',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 2, 17, 27, 54, 472254)),
        ),
    ]
