# Generated by Django 3.2.7 on 2022-01-02 15:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_api_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='api',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
